### ISSUE TITLE
Failing to create a new LDWizard application based on docs

### ISSUE THREAD

**Issue by WvandenBerg** [pldn/LDWizard#131]
## Steps to reproduce 
This is the first time I try to get an LDWizard app running since #99. I follow the instructions in [CONFIGURING.md](https://github.com/pldn/LDWizard/blob/main/CONFIGURING.md). Step 6 is where I get the following error. 

## Error message

```cmd
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\bergwvd\GitHub\LDWizard> npm install --global yarn

changed 1 package, and audited 2 packages in 2s

found 0 vulnerabilities
PS C:\Users\bergwvd\GitHub\LDWizard> mkdir my-wizard


    Directory: C:\Users\bergwvd\GitHub\LDWizard


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----          5-7-2023     08:53                my-wizard


PS C:\Users\bergwvd\GitHub\LDWizard> cd .\my-wizard\
PS C:\Users\bergwvd\GitHub\LDWizard\my-wizard> yarn add @pldn/ldwizard
yarn add v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/8] ⠁ waiting...
[-/8] ⠂ waiting...
[-/8] ⠂ waiting...
[4/8] ⠂ xpath-iterator
warning Error running install script for optional dependency: "C:\\Users\\bergwvd\\Prive\\Git\\GitHub\\LDWizard\\node_modules\\xpath-iterator: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: C:\\Users\\bergwvd\\Prive\\Git\\GitHub\\LDWizard\\node_modules\\xpath-iterator
Output:
C:\\Users\\bergwvd\\Prive\\Git\\GitHub\\LDWizard\\node_modules\\xpath-iterator>if not defined npm_config_node_gyp (node \"C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" rebuild )  else (node \"\" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@9.0.0
gyp info using node@16.17.0 | win32 | x64
gyp info find Python using Python version 3.10.4 found at \"C:\\Users\\bergwvd\\AppData\\Local\\Programs\\Python\\Python310\\python.exe\"
gyp http GET https://nodejs.org/download/release/v16.17.0/node-v16.17.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v16.17.0/node-v16.17.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v16.17.0/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v16.17.0/win-x86/node.lib
gyp http GET https://nodejs.org/download/release/v16.17.0/win-x64/node.lib
gyp http GET https://nodejs.org/download/release/v16.17.0/win-arm64/node.lib
gyp http 200 https://nodejs.org/download/release/v16.17.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v16.17.0/win-x86/node.lib
gyp http 200 https://nodejs.org/download/release/v16.17.0/win-x64/node.lib
gyp http 404 https://nodejs.org/download/release/v16.17.0/win-arm64/node.lib
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly'
for more details
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the \"Desktop development with C++\" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\lib\\find-visualstudio.js:122:47)
gyp ERR! stack     at C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\lib\\find-visualstudio.js:75:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\lib\\find-visualstudio.js:363:14)
gyp ERR! stack     at VisualStudioFinder.fail (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\lib\\find-visualstudio.js:122:47)
gyp ERR! stack     at C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\lib\\find-visualstudio.js:75:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\lib\\find-visualstudio.js:363:14)
gyp ERR! stack     at C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\lib\\find-visualstudio.js:71:14
gyp ERR! stack     at C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\lib\\find-visualstudio.js:384:16

gyp ERR! stack     at C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\lib\\util.js:54:7
gyp ERR! stack     at C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\lib\\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:408:5)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1093:16)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuild\"
gyp ERR! cwd C:\\Users\\bergwvd\\Prive\\Git\\GitHub\\LDWizard\\node_modules\\xpath-iterator
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ @pldn/ldwizard@2.2.0
info All dependencies
└─ @pldn/ldwizard@2.2.0
Done in 142.15s.
PS C:\Users\bergwvd\GitHub\LDWizard\my-wizard> yarn exec ldwizard-build config.ts
yarn exec v1.22.19
error Couldn't find the binary ldwizard-build
info Visit https://yarnpkg.com/en/docs/cli/exec for documentation about this command.
```

**Comment by philipperenzen** [comment]
Hello @WvandenBerg, 

Unfortunately there is a known issue with the `xpath-iterator` library on windows, which could be the underlying reason of your build error. This is caused by the sub dependency of the RocketRML library that is used for RML transformations, if this is the case, please create an issue here: https://github.com/semantifyit/RocketRML.

Otherwise it is recommended to use command prompt instead of powershell to run yarn commands, and to install the recommended tools for nodegyp (https://github.com/nodejs/node-gyp#on-windows), like Python and Visual Studio build tools (https://visualstudio.microsoft.com/downloads/?q=build+tools). 

Using a newer version of yarn could also prevent these installation errors (`yarn set version berry` should help).
